export interface Anyrun {
  task_id: string;
  iso_time: Date;
  date: Date;
  additional_time_used: string;
  autoconfirmation_of_uac: string;
  fakenet_option: string;
  file_info: string;
  file_name: string;
  full_analysis: string;
  heavy_evaision_option: string;
  indicators: string;
  md5: string;
  mine: string;
  mitm_proxy: string;
  network_geolocation: string;
  os: string;
  privacy: string;
  route_via_tor: string;
  sha1: string;
  sha256: string;
  ssdeep: string;
  tags: string;
  task_duration: string;
  threats: string;
  url: string;
  verdict: string;
  bot_code: string;
  bot_ip: string;
}
export const ANYRUN_INDEX = process.env.ANYRUN_INDEX;
